# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatingPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatingPractice

  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'TextFieldEffects'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'ObjectMapper', '~>2.2'

end
